# Generated by Django 5.2.2 on 2025-06-24 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('destination', models.CharField(max_length=255, verbose_name='Destino')),
                ('departure_time', models.TimeField(verbose_name='Hora de Partida')),
                ('arrival_time', models.TimeField(verbose_name='Hora de Chegada')),
                ('problems', models.TextField(blank=True, null=True, verbose_name='Problemas Encontrados')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='users.employee', verbose_name='Motorista')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='tasks.task', verbose_name='Tarefa')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='teams.team', verbose_name='Equipe')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='logistics.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Logística',
                'verbose_name_plural': 'Logísticas',
            },
        ),
    ]
