# Generated by Django 5.2.2 on 2025-06-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logistics',
        ),
    ]
