# Generated by Django 5.2.2 on 2025-06-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_delete_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_manutencao', 'Em Manutenção'), ('em_uso', 'Em Uso'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20, verbose_name='Status do Veículo'),
        ),
    ]
