# Generated by Django 5.2.2 on 2025-06-24 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Relatório')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('completed_tasks', models.ManyToManyField(blank=True, related_name='completed_reports', to='tasks.task', verbose_name='Tarefas Concluídas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.employee', verbose_name='Funcionário')),
                ('pending_tasks', models.ManyToManyField(blank=True, related_name='pending_reports', to='tasks.task', verbose_name='Tarefas Pendentes')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
