# Generated by Django 5.2.2 on 2025-06-24 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_measurement', models.DateField(auto_now_add=True, verbose_name='Data da Medição')),
                ('observations', models.TextField(verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='users.employee', verbose_name='Funcionário')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='works.work', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
            },
        ),
        migrations.CreateModel(
            name='ItemMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='EX: Janela 1 ou Porta 2', max_length=100, verbose_name='Identificador')),
                ('type', models.CharField(choices=[('janela', 'Janela'), ('porta', 'Porta'), ('sacada', 'Sacada'), ('fachada', 'Fachada'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Largura (cm)')),
                ('localization', models.CharField(choices=[('entrada', 'Entrada'), ('corredor', 'Corredor'), ('fachada', 'Fachada'), ('sala', 'Sala'), ('quarto', 'Quarto'), ('banheiro', 'Banheiro'), ('cozinha', 'Cozinha'), ('escritório', 'Escritório'), ('sala de estar', 'Sala de Estar'), ('sala de jantar', 'Sala de Jantar'), ('varanda', 'Varanda'), ('area gourmet', 'Área gourmet'), ('outro', 'Outro')], max_length=100, verbose_name='Localização')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Altura (cm)')),
                ('observations', models.TextField(verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_measurement', to='measurements.measurement', verbose_name='Medição')),
            ],
            options={
                'verbose_name': 'Item de Medição',
                'verbose_name_plural': 'Itens de Medição',
            },
        ),
    ]
