# Generated by Django 5.2.2 on 2025-06-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_measurement',
            field=models.DateField(verbose_name='Data da Medição'),
        ),
    ]
