# Generated by Django 5.2.2 on 2025-06-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_alter_measurement_date_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmeasurement',
            name='localization',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('corredor', 'Corredor'), ('fachada', 'Fachada'), ('sala', 'Sala'), ('quarto', 'Quarto'), ('banheiro', 'Banheiro'), ('cozinha', 'Cozinha'), ('escritório', 'Escritório'), ('sala_de_estar', 'Sala de Estar'), ('sala_de_jantar', 'Sala de Jantar'), ('varanda', 'Varanda'), ('area_gourmet', 'Área gourmet'), ('outro', 'Outro')], max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='itemmeasurement',
            name='type',
            field=models.CharField(choices=[('janela', 'Janela'), ('porta', 'Porta'), ('sacada', 'Sacada'), ('portão', 'Portão'), ('fachada', 'Fachada'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
