# Generated by Django 5.2.2 on 2025-07-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_itemmeasurement_localization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmeasurement',
            name='type',
            field=models.CharField(choices=[('janela', 'Janela'), ('porta', 'Porta'), ('box', 'Box'), ('sacada', 'Sacada'), ('portão', 'Portão'), ('fachada', 'Fachada'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
